setwd("~/Desktop/Purna/MB/MB-onegraph/coverage/new-correct2/")
#load("covg-res-new-sbm-n500-3.RData")
load("covg-res-6taus-sbm.RData")
#tau_n_list=c(0.05,0.06,0.07,0.08,0.09,0.2,0.4,0.6,0.8,1.0)
tau_n_list=c(0.05,0.07,0.09,0.2,0.6,1.0)

pdf("corrected-triangles-sbm.pdf",width=5,height=2.5)
par(mar=c(4,4,3,2))
plot(tau_n_list,res$covg_sbm_triangles[,1],type='l',col='blue',ylim=c(85,100))
lines(tau_n_list,res$covg_sbm_triangles[,2],col='red')
lines(tau_n_list,res$covg_sbm_triangles[,3],col=5)
lines(tau_n_list,res$covg_sbm_triangles[,4],col=8)
lines(tau_n_list,res$covg_sbm_triangles[,5],col=7)
lines(tau_n_list,res$covg_sbm_triangles[,6],col='orange')
abline(h=95,lty=2)
#legend(0,90,legend=c("MB-Q","MB-L","LS","SS","EG","MB-L-apx"),lty=c(1,1,1,1,1,1),col=c('blue','red',5,8,7,'orange'),cex=0.7,bty = 'n')
legend(0,90,legend=c("MB-Q","MB-L"),lty=c(1,1),col=c('blue','red'),cex=0.7,bty = 'n')
legend(0.3,90,legend=c("LS","SS"),lty=c(1,1),col=c(5,8),cex=0.7,bty = 'n')
legend(0.5,90,legend=c("EG","MB-L-apx"),lty=c(1,1),col=c(7,'orange'),cex=0.7,bty = 'n')
dev.off()


pdf("corrected-vs-sbm.pdf",width=5,height=2.5)
par(mar=c(4,4,3,2))
plot(tau_n_list,res$covg_sbm_vs[,1],type='l',col='blue',ylim=c(85,100))
lines(tau_n_list,res$covg_sbm_vs[,2],col='red')
lines(tau_n_list,res$covg_sbm_vs[,3],col=5)
lines(tau_n_list,res$covg_sbm_vs[,4],col=8)
lines(tau_n_list,res$covg_sbm_vs[,5],col=7)
lines(tau_n_list,res$covg_sbm_vs[,6],col='orange')
abline(h=95,lty=2)
legend(0,90,legend=c("MB-Q","MB-L"),lty=c(1,1),col=c('blue','red'),cex=0.7,bty = 'n')
legend(0.3,90,legend=c("LS","SS"),lty=c(1,1),col=c(5,8),cex=0.7,bty = 'n')
legend(0.5,90,legend=c("EG","MB-L-apx"),lty=c(1,1),col=c(7,'orange'),cex=0.7,bty = 'n')
dev.off()

pdf("correct-v-nocorrect-triangles-sbm.pdf",width=5,height=2.5)
par(mar=c(4,4,3,2))
plot(tau_n_list,res$covg_sbm_triangles[,1],col='blue',type='l',cex=0.7,ylim=c(85,100))
lines(tau_n_list,res$covg_sbm_triangles_old[,1],col='blue',lty=2)
lines(tau_n_list,res$covg_sbm_triangles[,4],col=8)
lines(tau_n_list,res$covg_sbm_triangles_old[,4],col=8,lty=2)
lines(tau_n_list,res$covg_sbm_triangles[,5],col=7)
lines(tau_n_list,res$covg_sbm_triangles_old[,5],col=7,lty=2)
abline(h=95,lty=2)
legend(0,90,legend=c("MB-Q","MB-Q-nocrt"),lty=c(1,2),col=c('blue','blue'),cex=0.7,bty = 'n')
legend(0.3,90,legend=c("SS","SS-nocrt"),lty=c(1,2),col=c(8,8),cex=0.7,bty = 'n')
legend(0.5,90,legend=c("EG","EG-nocrt"),lty=c(1,2),col=c(7,7),cex=0.7,bty = 'n')
dev.off()



pdf("correct-v-nocorrect-vs-sbm.pdf",width=5,height=2.5)
par(mar=c(4,4,3,2))
plot(tau_n_list,res$covg_sbm_vs[,1],col='blue',type='l',cex=0.7,ylim=c(85,100))
lines(tau_n_list,res$covg_sbm_vs_old[,1],col='blue',lty=2)
lines(tau_n_list,res$covg_sbm_vs[,4],col=8)
lines(tau_n_list,res$covg_sbm_vs_old[,4],col=8,lty=2)
lines(tau_n_list,res$covg_sbm_vs[,5],col=7)
lines(tau_n_list,res$covg_sbm_vs_old[,5],col=7,lty=2)
abline(h=95,lty=2)
legend(0,90,legend=c("MB-Q","MB-Q-nocrt"),lty=c(1,2),col=c('blue','blue'),cex=0.7,bty = 'n')
legend(0.3,90,legend=c("SS","SS-nocrt"),lty=c(1,2),col=c(8,8),cex=0.7,bty = 'n')
legend(0.5,90,legend=c("EG","EG-nocrt"),lty=c(1,2),col=c(7,7),cex=0.7,bty = 'n')
dev.off()



pdf("corrected-trans-sbm.pdf",width=5,height=2.5)
par(mar=c(4,4,3,2))
plot(tau_n_list,res$covg_sbm_trans[,1],type='l',col='blue',ylim=c(85,100))
lines(tau_n_list,res$covg_sbm_trans[,2],col='red')
lines(tau_n_list,res$covg_sbm_trans[,3],col=5)
lines(tau_n_list,res$covg_sbm_trans[,4],col=8)
lines(tau_n_list,res$covg_sbm_trans[,5],col=7)
lines(tau_n_list,res$covg_sbm_trans[,6],col='orange')
abline(h=95,lty=2)
#legend(0,90,legend=c("MB-Q","MB-L","LS","SS","EG","MB-L-apx"),lty=c(1,1,1,1,1,1),col=c('blue','red',5,8,7,'orange'),cex=0.7,bty = 'n')
legend(0,90,legend=c("MB-Q","MB-L"),lty=c(1,1),col=c('blue','red'),cex=0.7,bty = 'n')
legend(0.3,90,legend=c("LS","SS"),lty=c(1,1),col=c(5,8),cex=0.7,bty = 'n')
legend(0.5,90,legend=c("EG","MB-L-apx"),lty=c(1,1),col=c(7,'orange'),cex=0.7,bty = 'n')
dev.off()

pdf("correct-v-nocorrect-trans-sbm.pdf",width=5,height=2.5)
par(mar=c(4,4,3,2))
plot(tau_n_list,res$covg_sbm_trans[,1],col='blue',type='l',cex=0.7,ylim=c(85,100))
lines(tau_n_list,res$covg_sbm_trans_old[,1],col='blue',lty=2)
lines(tau_n_list,res$covg_sbm_trans[,4],col=8)
lines(tau_n_list,res$covg_sbm_trans_old[,4],col=8,lty=2)
lines(tau_n_list,res$covg_sbm_trans[,5],col=7)
lines(tau_n_list,res$covg_sbm_trans_old[,5],col=7,lty=2)
abline(h=95,lty=2)
legend(0,90,legend=c("MB-Q","MB-Q-nocrt"),lty=c(1,2),col=c('blue','blue'),cex=0.7,bty = 'n')
legend(0.3,90,legend=c("SS","SS-nocrt"),lty=c(1,2),col=c(8,8),cex=0.7,bty = 'n')
legend(0.5,90,legend=c("EG","EG-nocrt"),lty=c(1,2),col=c(7,7),cex=0.7,bty = 'n')
dev.off()

